In [40]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import GridSearchCV

In [11]:
df=pd.read_csv("road_network.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=200, step=1)
All columns are
0 road_id
1 road_name
2 road_type
3 length_km
4 lanes
5 speed_limit_kmh
6 capacity_vehicles_per_hour
7 has_bus_lane
8 has_bike_lane
9 surface_condition
10 last_maintenance_date
11 latitude_start
12 longitude_start
13 latitude_end
14 longitude_end
15 district
16 toll_rate_rp
17 avg_daily_traffic

In [12]:
df.shape

(200, 18)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   road_id                     200 non-null    object
 1   road_name                   200 non-null    object
 2   road_type                   200 non-null    object
 3   length_km                   200 non-null    float64
 4   lanes                       200 non-null    int64
 5   speed_limit_kmh             200 non-null    int64
 6   capacity_vehicles_per_hour  200 non-null    int64
 7   has_bus_lane                200 non-null    int64
 8   has_bike_lane               200 non-null    int64
 9   surface_condition           200 non-null    object
 10  last_maintenance_date       200 non-null    object
 11  latitude_start              200 non-null    float64
 12  longitude_start             200 non-null    float64
 13  latitude_end                200 non-null    float64
 14  longitude_end               200 non-null    float64
 15  district                    200 non-null    object
 16  toll_rate_rp                200 non-null    int64
 17  avg_daily_traffic           200 non-null    int64
dtypes: float64(5), int64(7), object(6)
memory usage: 28.3+ KB

In [14]:
for i in df.select_dtypes(include=['object', 'string']):
    counts = df[i].value_counts()
    print(counts)

road_id
RD-0001    1
RD-0138    1
RD-0128    1
RD-0129    1
RD-0130    1
          ..
RD-0070    1
RD-0071    1
RD-0072    1
RD-0073    1
RD-0200    1
Name: count, Length: 200, dtype: int64
road_name
Jl. Segment 1      1
Jl. Segment 138    1
Jl. Segment 128    1
Jl. Segment 129    1
Jl. Segment 130    1
                  ..
Jl. Segment 70     1
Jl. Segment 71     1
Jl. Segment 72     1
Jl. Segment 73     1
Jl. Segment 200    1
Name: count, Length: 200, dtype: int64
road_type
Jalan Tol           48
Jalan Lingkungan    46
Jalan Kolektor      44
Jalan Lokal         33
Jalan Arteri        29
Name: count, dtype: int64
surface_condition
Baik            106
Cukup            61
Rusak Ringan     23
Rusak Berat      10
Name: count, dtype: int64
last_maintenance_date
2022-08-10    3
2023-02-05    3
2022-12-21    2
2022-12-18    2
2023-12-23    2
             ..
2023-05-01    1
2022-09-16    1
2022-06-03    1
2023-07-30    1
2024-01-01    1
Name: count, Length: 173, dtype: int64
district
Mangga Dua       18
PIK              16
Menteng          16
Senen            14
Depok            13
Kuningan         12
Sudirman         12
Bekasi           11
Cawang           10
Cibubur          10
Kelapa Gading     9
Blok M            9
Senayan           8
Grogol            8
Sunter            7
Pluit             6
Cakung            6
Slipi             5
Tangerang         5
Kemang            5
Name: count, dtype: int64

In [35]:
# Features and target seperation
X = df.drop(
    columns=[
        'avg_daily_traffic',
        'last_maintenance_date',
        'road_id',
        'road_name'
    ],
    errors='ignore'
)

y = df['avg_daily_traffic']

In [36]:
# Training a general random forest
categorical_cols = X.select_dtypes(include='object').columns


preprocessor = ColumnTransformer([
    ('cat',
     OneHotEncoder(drop='first', handle_unknown='ignore'),
     categorical_cols)
], remainder='passthrough')


rf_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

In [37]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)


rf_pipe.fit(X_train, y_train)


print("Train R²:", rf_pipe.score(X_train, y_train))
print("Test R²:", rf_pipe.score(X_test, y_test))

Train R²: 0.9776422717895181
Test R²: 0.839459557349774

In [38]:
# Cross Validation

cv_scores = cross_val_score(
    rf_pipe,
    X,
    y,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

print("\nCV Scores:", cv_scores)
print("Mean CV R²:", cv_scores.mean())

CV Scores: [0.78869393 0.78379203 0.81961197 0.85236833 0.82407679]
Mean CV R²: 0.8137086118124731

In [41]:
# Hyperparameter Tuning

params = {
    'model__n_estimators': [100, 200, 300],
    'model__max_depth': [None, 5, 10, 15],
    'model__min_samples_split': [2, 5, 10],
    'model__min_samples_leaf': [1, 2, 4]
}

grid = GridSearchCV(
    rf_pipe,
    params,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Params: {'model__max_depth': 5, 'model__min_samples_leaf': 1, 'model__min_samples_split': 5, 'model__n_estimators': 100}
Best CV Score: 0.8342341127172095

In [44]:
results = pd.DataFrame(grid.cv_results_)

top_results = (
    results[
        [
            'mean_test_score',
            'param_model__n_estimators',
            'param_model__max_depth',
            'param_model__min_samples_split',
            'param_model__min_samples_leaf'
        ]
    ]
    .sort_values('mean_test_score', ascending=False)
    .reset_index(drop=True)
)

top_results.head(10)

,mean_test_score,param_model__n_estimators,param_model__max_depth,param_model__min_samples_split,param_model__min_samples_leaf
0,0.834234,100,5,5,1
1,0.833948,200,5,2,1
2,0.833845,100,5,2,1
3,0.833161,100,10,5,1
4,0.832443,300,5,2,1
5,0.832047,200,5,5,1
6,0.831495,100,15,5,1
7,0.831492,100,None,5,1
8,0.829775,300,5,5,1
9,0.829733,100,15,2,1

In [45]:
# Hyperparameter Tuning Again using the previous result information for next one

params = {
    'model__n_estimators': [50,75,100,125,150,175,200],
    'model__max_depth': [1,2,4,5,6,8],
    'model__min_samples_split': [1,2,3,4,5],
    'model__min_samples_leaf': [1, 2,3,4]
}

grid = GridSearchCV(
    rf_pipe,
    params,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
840 fits failed out of a total of 4200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
840 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 662, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of RandomForestRegressor must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan 0.69976355 0.69799492 0.70178838 0.70372126 0.70468988
 0.70356327 0.70374307 0.69976355 0.69799492 0.70178838 0.70372126
 0.70468988 0.70356327 0.70374307 0.69976355 0.69799492 0.70178838
 0.70372126 0.70468988 0.70356327 0.70374307 0.69976355 0.69799492
 0.70178838 0.70372126 0.70468988 0.70356327 0.70374307        nan
        nan        nan        nan        nan        nan        nan
 0.69976355 0.69799492 0.70178838 0.70372126 0.70468988 0.70356327
 0.70374307 0.69976355 0.69799492 0.70178838 0.70372126 0.70468988
 0.70356327 0.70374307 0.69976355 0.69799492 0.70178838 0.70372126
 0.70468988 0.70356327 0.70374307 0.69976355 0.69799492 0.70178838
 0.70372126 0.70468988 0.70356327 0.70374307        nan        nan
        nan        nan        nan        nan        nan 0.69976355
 0.69799492 0.70178838 0.70372126 0.70456734 0.70348788 0.70369233
 0.69976355 0.69799492 0.70178838 0.70372126 0.70456734 0.70348788
 0.70369233 0.69976355 0.69799492 0.70178838 0.70372126 0.70456734
 0.70348788 0.70369233 0.69976355 0.69799492 0.70178838 0.70372126
 0.70456734 0.70348788 0.70369233        nan        nan        nan
        nan        nan        nan        nan 0.69976355 0.69799492
 0.70178838 0.70372126 0.70456734 0.70348788 0.70369233 0.69976355
 0.69799492 0.70178838 0.70372126 0.70456734 0.70348788 0.70369233
 0.69976355 0.69799492 0.70178838 0.70372126 0.70456734 0.70348788
 0.70369233 0.69976355 0.69799492 0.70178838 0.70372126 0.70456734
 0.70348788 0.70369233        nan        nan        nan        nan
        nan        nan        nan 0.80703341 0.80540795 0.8057038
 0.80555532 0.80573812 0.80645796 0.80728883 0.80703341 0.80540795
 0.8057038  0.80555532 0.80568687 0.80641442 0.8072517  0.80703341
 0.80540795 0.8057038  0.80555532 0.80568687 0.80641442 0.8072517
 0.80703341 0.80540795 0.8057038  0.80555532 0.80568687 0.80641442
 0.8072517         nan        nan        nan        nan        nan
        nan        nan 0.80254705 0.79871778 0.79954153 0.80138765
 0.80198196 0.80261832 0.80325345 0.80254705 0.79871778 0.79954153
 0.80138765 0.80198196 0.80261832 0.80325345 0.80254705 0.79871778
 0.79954153 0.80138765 0.80198196 0.80261832 0.80325345 0.80254705
 0.79871778 0.79954153 0.80138765 0.80198196 0.80261832 0.80325345
        nan        nan        nan        nan        nan        nan
        nan 0.78987364 0.78615273 0.78789461 0.78852659 0.7882166
 0.78968436 0.79056225 0.78987364 0.78615273 0.78789461 0.78852659
 0.7882166  0.78968436 0.79056225 0.78987364 0.78615273 0.78789461
 0.78852659 0.7882166  0.78968436 0.79056225 0.78987364 0.78615273
 0.78789461 0.78852659 0.7882166  0.78968436 0.79056225        nan
        nan        nan        nan        nan        nan        nan
 0.78710806 0.78437913 0.78621925 0.78718238 0.78618718 0.78655455
 0.78800062 0.78710806 0.78437913 0.78621925 0.78718238 0.78618718
 0.78655455 0.78800062 0.78710806 0.78437913 0.78621925 0.78718238
 0.78618718 0.78655455 0.78800062 0.78710806 0.78437913 0.78621925
 0.78718238 0.78618718 0.78655455 0.78800062        nan        nan
        nan        nan        nan        nan        nan 0.82861328
 0.8286134  0.82887155 0.83068918 0.83318726 0.83132381 0.831488
 0.82985252 0.8264093  0.82585881 0.82826457 0.83168014 0.83073868
 0.83066243 0.82782895 0.82570998 0.82577583 0.82791551 0.83132828
 0.83036263 0.82997443 0.82789007 0.82650246 0.82590923 0.82562163
 0.82842162 0.82793764 0.82761488        nan        nan        nan
        nan        nan        nan        nan 0.81148973 0.81299063
 0.81353507 0.81552828 0.81638797 0.81494676 0.81473166 0.81148973
 0.81299063 0.81353507 0.81552828 0.81638797 0.81494676 0.81473166
 0.81148973 0.81299063 0.81353507 0.81552828 0.81638797 0.81494676
 0.81473166 0.81089109 0.81302315 0.81295719 0.81529508 0.81613339
 0.81510061 0.81499356        nan        nan        nan        nan
        nan        nan        nan 0.78308607 0.77906731 0.78165074
 0.78469568 0.78419112 0.78419691 0.78533553 0.78308607 0.77906731
 0.78165074 0.78469568 0.78419112 0.78419691 0.78533553 0.78308607
 0.77906731 0.78165074 0.78469568 0.78419112 0.78419691 0.78533553
 0.78308607 0.77906731 0.78165074 0.78469568 0.78419112 0.78419691
 0.78533553        nan        nan        nan        nan        nan
        nan        nan 0.7810066  0.78128643 0.78300642 0.7859975
 0.78437829 0.78410467 0.78478086 0.7810066  0.78128643 0.78300642
 0.7859975  0.78437829 0.78410467 0.78478086 0.7810066  0.78128643
 0.78300642 0.7859975  0.78437829 0.78410467 0.78478086 0.7810066
 0.78128643 0.78300642 0.7859975  0.78437829 0.78410467 0.78478086
        nan        nan        nan        nan        nan        nan
        nan 0.82690714 0.83215036 0.83384541 0.83438737 0.83507738
 0.83353014 0.83394768 0.82438056 0.82866238 0.83339652 0.83385722
 0.83343208 0.83252518 0.83168634 0.82334909 0.82457302 0.82546548
 0.8269052  0.82773789 0.82735614 0.82638327 0.82661313 0.83323186
 0.83423411 0.83470726 0.83397301 0.83323562 0.83204702        nan
        nan        nan        nan        nan        nan        nan
 0.80789205 0.8087776  0.81045214 0.81400292 0.81522615 0.81357819
 0.81333064 0.80789205 0.8087776  0.81045214 0.81400292 0.81522615
 0.81357819 0.81333064 0.80789205 0.8087776  0.81045214 0.81400292
 0.81522615 0.81357819 0.81333064 0.8079238  0.81054056 0.81106315
 0.81472186 0.81587325 0.81426648 0.81405367        nan        nan
        nan        nan        nan        nan        nan 0.78136508
 0.77745061 0.7794303  0.78366346 0.78402324 0.78344368 0.78482705
 0.78136508 0.77745061 0.7794303  0.78366346 0.78402324 0.78344368
 0.78482705 0.78136508 0.77745061 0.7794303  0.78366346 0.78402324
 0.78344368 0.78482705 0.78136508 0.77745061 0.7794303  0.78366346
 0.78402324 0.78344368 0.78482705        nan        nan        nan
        nan        nan        nan        nan 0.78015061 0.77975067
 0.78158062 0.78541414 0.78357329 0.78351105 0.78432915 0.78015061
 0.77975067 0.78158062 0.78541414 0.78357329 0.78351105 0.78432915
 0.78015061 0.77975067 0.78158062 0.78541414 0.78357329 0.78351105
 0.78432915 0.78015061 0.77975067 0.78158062 0.78541414 0.78357329
 0.78351105 0.78432915        nan        nan        nan        nan
        nan        nan        nan 0.82871014 0.82881628 0.83203623
 0.83169275 0.83372194 0.8328898  0.83187097 0.83117351 0.83280089
 0.83550184 0.83505832 0.83486254 0.83248235 0.83300792 0.82494923
 0.82827025 0.8296358  0.83133211 0.83320415 0.83113808 0.83019507
 0.82807499 0.83154292 0.83229869 0.83196133 0.8333835  0.83144332
 0.83142048        nan        nan        nan        nan        nan
        nan        nan 0.80699136 0.80992535 0.81162323 0.81445474
 0.81584281 0.81415006 0.81306605 0.80699136 0.80992535 0.81162323
 0.81445474 0.81584281 0.81415006 0.81306605 0.80699136 0.80992535
 0.81162323 0.81445474 0.81584281 0.81415006 0.81306605 0.80705228
 0.80808208 0.80944649 0.81266563 0.81385945 0.81261747 0.81204136
        nan        nan        nan        nan        nan        nan
        nan 0.77942552 0.77694512 0.7791754  0.78286461 0.782971
 0.78275817 0.78379061 0.77942552 0.77694512 0.7791754  0.78286461
 0.782971   0.78275817 0.78379061 0.77942552 0.77694512 0.7791754
 0.78286461 0.782971   0.78275817 0.78379061 0.77942552 0.77694512
 0.7791754  0.78286461 0.782971   0.78275817 0.78379061        nan
        nan        nan        nan        nan        nan        nan
 0.78186028 0.78072712 0.78215196 0.78632591 0.78426218 0.783834
 0.78440312 0.78186028 0.78072712 0.78215196 0.78632591 0.78426218
 0.783834   0.78440312 0.78186028 0.78072712 0.78215196 0.78632591
 0.78426218 0.783834   0.78440312 0.78186028 0.78072712 0.78215196
 0.78632591 0.78426218 0.783834   0.78440312        nan        nan
        nan        nan        nan        nan        nan 0.81758302
 0.82327175 0.82264677 0.82495734 0.8289376  0.82771592 0.82665498
 0.82059844 0.82496427 0.82657768 0.82638659 0.82731217 0.82719898
 0.82711671 0.82763237 0.83074773 0.83108256 0.82962404 0.82954812
 0.82886137 0.8280245  0.8167746  0.82312487 0.82533866 0.82723131
 0.82852534 0.82687026 0.82693531        nan        nan        nan
        nan        nan        nan        nan 0.80672373 0.80791636
 0.8099163  0.81346809 0.81480423 0.81352781 0.81267523 0.80672373
 0.80791636 0.8099163  0.81346809 0.81480423 0.81352781 0.81267523
 0.80672373 0.80791636 0.8099163  0.81346809 0.81480423 0.81352781
 0.81267523 0.80461536 0.8067368  0.80814858 0.81119842 0.81238952
 0.81115455 0.8110007         nan        nan        nan        nan
        nan        nan        nan 0.77984125 0.77667051 0.77932604
 0.78251527 0.78256264 0.78244749 0.78377918 0.77984125 0.77667051
 0.77932604 0.78251527 0.78256264 0.78244749 0.78377918 0.77984125
 0.77667051 0.77932604 0.78251527 0.78256264 0.78244749 0.78377918
 0.77984125 0.77667051 0.77932604 0.78251527 0.78256264 0.78244749
 0.78377918        nan        nan        nan        nan        nan
        nan        nan 0.78174868 0.78047463 0.78196982 0.78612759
 0.78427043 0.78388311 0.78444653 0.78174868 0.78047463 0.78196982
 0.78612759 0.78427043 0.78388311 0.78444653 0.78174868 0.78047463
 0.78196982 0.78612759 0.78427043 0.78388311 0.78444653 0.78174868
 0.78047463 0.78196982 0.78612759 0.78427043 0.78388311 0.78444653]
  warnings.warn(

Best Params: {'model__max_depth': 6, 'model__min_samples_leaf': 1, 'model__min_samples_split': 3, 'model__n_estimators': 100}
Best CV Score: 0.8355018383617943

In [46]:
results = pd.DataFrame(grid.cv_results_)

top_results = (
    results[
        [
            'mean_test_score',
            'param_model__n_estimators',
            'param_model__max_depth',
            'param_model__min_samples_split',
            'param_model__min_samples_leaf'
        ]
    ]
    .sort_values('mean_test_score', ascending=False)
    .reset_index(drop=True)
)

top_results.head(10)

,mean_test_score,param_model__n_estimators,param_model__max_depth,param_model__min_samples_split,param_model__min_samples_leaf
0,0.835502,100,6,3,1
1,0.835077,150,5,2,1
2,0.835058,125,6,3,1
3,0.834863,150,6,3,1
4,0.834707,125,5,5,1
5,0.834387,125,5,2,1
6,0.834234,100,5,5,1
7,0.833973,150,5,5,1
8,0.833948,200,5,2,1
9,0.833857,125,5,3,1

In [49]:
print("Best Params:", grid.best_params_)

Best Params: {'model__max_depth': 6, 'model__min_samples_leaf': 1, 'model__min_samples_split': 3, 'model__n_estimators': 100}

In [51]:
# Best Model is 

categorical_cols = X.select_dtypes(include='object').columns


preprocessor = ColumnTransformer([
    ('cat',
     OneHotEncoder(drop='first', handle_unknown='ignore'),
     categorical_cols)
], remainder='passthrough')


rf_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=100,
        max_depth=6,
        min_samples_leaf=1,
        min_samples_split=3,
        n_jobs=-1
    ))
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)


rf_pipe.fit(X_train, y_train)


print("Train R²:", rf_pipe.score(X_train, y_train))
print("Test R²:", rf_pipe.score(X_test, y_test))


cv_scores = cross_val_score(
    rf_pipe,
    X,
    y,
    cv=10,
    scoring='r2',
    n_jobs=-1
)

print("\nCV Scores:", cv_scores)
print("Mean CV R²:", cv_scores.mean())

Train R²: 0.9667072149652194
Test R²: 0.7973466506924081

CV Scores: [0.84766072 0.70214267 0.80731012 0.72353614 0.75112094 0.88071575
 0.81712811 0.91869152 0.93734492 0.7941172 ]
Mean CV R²: 0.817976808411936